# Generated by Django 5.0.4 on 2024-04-09 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_project_project_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.project'),
        ),
    ]
