# Generated by Django 5.0.4 on 2024-04-11 15:20

import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_favorite_projects_alter_favorite_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_img',
            field=models.ImageField(blank=True, null=True, upload_to=main_app.models.upload_to),
        ),
    ]
