# Generated by Django 5.0.4 on 2024-04-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_project_project_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('T', 'Tech'), ('C', 'Carpentry'), ('R', 'Renovations'), ('A', 'Art & Design'), ('J', 'Jewelery'), ('H', 'Homegoods')], default='T', max_length=1),
        ),
    ]
