# Generated by Django 5.0.4 on 2024-04-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_img',
            field=models.CharField(default='soup', max_length=250),
            preserve_default=False,
        ),
    ]
